/**
 * Every user-facing string in the web app, in one place. Change wording here —
 * never inline a label/toast/placeholder in a component or template.
 */
export const COPY = {
  common: {
    cancel: 'Cancel',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    previousMonth: 'Previous month',
    nextMonth: 'Next month',
    genericError: 'Something went wrong. Please try again.',
  },

  nav: {
    dashboard: 'Dashboard',
    transactions: 'Transactions',
    add: 'Add Transaction',
    scan: 'Scan Receipt',
    import: 'Import Statement',
    budgets: 'Budgets',
    analytics: 'Analytics',
    reports: 'Reports',
    settings: 'Settings',
  },

  shell: {
    greeting: (name: string) => `Good morning, ${name} 👋`,
    titles: {
      dashboardSub: 'Your money at a glance',
      transactions: { title: 'Transactions', sub: 'Every rupee, accounted for' },
      add: { title: 'Add transaction', sub: 'Log an expense or income in seconds' },
      scan: { title: "Snap it, we'll do the typing", sub: 'Scan a receipt to auto-fill a transaction' },
      import: { title: 'Bring in your bank data securely', sub: 'Import a statement export from your bank' },
      budgets: { title: 'Budgets', sub: 'Keep every category on track' },
      analytics: { title: 'Analytics', sub: 'Where your money really goes' },
      reports: { title: 'Reports', sub: 'Export clean summaries of your finances' },
      settings: { title: 'Settings', sub: 'Profile, preferences and privacy' },
    },
    privacyTitle: 'Bank-grade privacy',
    privacyBody: 'Raw statements are masked and never stored permanently.',
    searchPlaceholder: 'Search transactions…',
    logout: 'Log out',
    addBtn: 'Add',
  },

  dashboard: {
    greeting: (name: string) => `Here's your money at a glance, ${name}.`,
    totalBalance: 'Total balance',
    savedLabel: 'saved',
    thisMonthSuffix: 'this month',
    income: 'Income',
    incomeSub: 'This month',
    expenses: 'Expenses',
    expensesSub: (count: number) => `Across ${count} categories`,
    saved: 'Saved',
    savedSub: (pct: number) => `${pct}% of income`,
    quickActions: {
      addExpense: { title: 'Add Expense', sub: 'Log it in seconds' },
      scanReceipt: { title: 'Scan Receipt', sub: 'Auto-read totals' },
      importStatement: { title: 'Import Statement', sub: 'CSV from your bank' },
      viewReport: { title: 'View Report', sub: 'Monthly summary' },
    },
    spendingByCategory: 'Spending by category',
    details: 'Details',
    totalSpent: 'Total spent',
    monthlyBudget: 'Monthly budget',
    pctUsedSuffix: 'used',
    leftSuffix: 'left',
    viewAll: 'View all',
    seeInsights: 'See insights',
    nothingSpentTitle: 'Nothing spent yet',
    nothingSpentHint: 'Your category breakdown shows up once you log expenses.',
    noTransactionsTitle: 'No transactions yet',
    noTransactionsHint: 'Add your first expense and it will show up here.',
    recentTransactions: 'Recent transactions',
  },

  addTransaction: {
    expense: 'Expense',
    income: 'Income',
    amountLabel: 'Amount',
    merchantLabel: 'Merchant / Source',
    dateLabel: 'Date',
    categoryLabel: 'Category',
    paymentMethodLabel: 'Payment method',
    attachReceiptLabel: 'Attach receipt',
    notesLabel: 'Notes',
    notesOptional: '(optional)',
    notesPlaceholder: 'Add a note…',
    newCategoryPlaceholder: 'e.g. Education, Pets, Gifts…',
    addBtn: 'Add',
    newCategory: 'New category',
    scanOrUpload: 'Scan or upload',
    livePreview: 'Live preview',
    merchantFallback: 'Merchant',
    todayLabel: 'Today',
    quickTips: 'Quick tips',
    tips: [
      'Scanning a receipt fills these fields automatically',
      'We auto-suggest a category from the merchant',
      "Everything can be edited before it's saved",
    ],
    saveBtn: 'Save transaction',
    paymentMethods: ['UPI · GPay', 'UPI · PhonePe', 'Credit card', 'Debit card', 'Cash', 'Bank transfer'],
    toasts: {
      enterCategoryName: 'Enter a category name',
      categoryAdded: 'Category added',
      couldNotAddCategory: 'Could not add category',
      enterAmount: 'Enter an amount greater than 0',
      enterMerchant: 'Enter a merchant or source',
      pickCategory: 'Pick a category',
      transactionSaved: 'Transaction saved',
      couldNotSave: 'Could not save transaction',
    },
  },

  transactions: {
    tabs: { all: 'All', income: 'Income', expenses: 'Expenses' },
    searchPlaceholder: 'Search by merchant…',
    tableHeaders: { merchant: 'Merchant', category: 'Category', date: 'Date', amount: 'Amount' },
    noMatchesTitle: 'No matches',
    noMatchesHint: 'Try a different search or filter.',
    deleteConfirm: (merchant: string) => `Delete "${merchant}"? This can't be undone.`,
    toasts: {
      merchantEmpty: 'Merchant cannot be empty',
      invalidAmount: 'Enter a valid amount',
      updated: 'Transaction updated',
      couldNotUpdate: 'Could not update transaction',
      deleted: 'Transaction deleted',
      couldNotDelete: 'Could not delete transaction',
    },
  },

  budgets: {
    heroKickerPrefix: 'Monthly budget ·',
    of: 'of',
    heroSubSuffix: 'left to spend · resets on the 1st',
    editBudgets: 'Edit budgets',
    emptyTitle: 'No budgets yet',
    emptyHint: 'Set a monthly limit per category to start tracking.',
    status: { onTrack: 'On track', close: 'Close', over: 'Over' },
    pctUsedSuffix: 'used',
    leftSuffix: 'left',
    overByPrefix: 'Over by',
    saveBudgets: 'Save budgets',
    toasts: {
      couldNotLoad: 'Could not load budgets',
      updated: 'Budgets updated',
      couldNotSave: 'Could not save budgets',
    },
  },

  analytics: {
    spendingTrend: 'Spending trend',
    trendSubtitle: (avg: string) => `Last 6 months · avg ${avg}/mo`,
    expensesKey: 'Expenses',
    categoryBreakdown: 'Category breakdown',
    noSpendingNote: 'No spending yet this month.',
    incomeVsExpense: 'Income vs expense',
    income: 'Income',
    expenses: 'Expenses',
    netSaved: 'Net saved',
    topMerchants: 'Top merchants',
    noMerchantsNote: 'No merchants yet this month.',
    subscriptions: 'Subscriptions',
    noSubscriptionsNote: 'No subscriptions this month.',
    monthlyCadence: 'Monthly',
  },

  reports: {
    generateReport: 'Generate a report',
    dateRange: 'Date range',
    format: 'Format',
    include: 'Include',
    presets: {
      thisMonth: 'This month',
      lastMonth: 'Last month',
      last3Months: 'Last 3 months',
      thisYear: 'This year',
    },
    formats: {
      pdf: { label: 'PDF', sub: 'Formatted report' },
      csv: { label: 'CSV', sub: 'Raw spreadsheet' },
    },
    includeOptions: ['Transaction list', 'Category summary', 'Budget vs actual', 'Charts & insights'],
    exportBtn: (fmt: 'PDF' | 'CSV') => `Export ${fmt}`,
    summary: 'Summary',
    incomeRow: 'Income',
    expensesRow: 'Expenses',
    netSavedRow: 'Net saved',
    transactionsRow: 'Transactions',
    topCategoryRow: 'Top category',
    recentExports: 'Recent exports',
    noExports: 'No exports yet',
    downloadAria: 'Download',
    downloadFilename: (format: string) => `SpendWise-report.${format}`,
    toasts: {
      couldNotLoadSummary: 'Could not load report summary',
      savedToDownloadsOnly: 'Saved to downloads history only',
      exported: 'Report exported · check downloads',
      exportFailed: 'Export failed',
    },
  },

  importStatement: {
    uploadTitle: 'Upload a bank statement',
    uploadSub: 'Drop a CSV export from your bank',
    chooseFile: 'Choose file',
    useSample: 'Use a sample statement',
    privacyTitle: 'Your data stays private',
    privacyBodyBefore: 'Sensitive details are masked and raw files are',
    privacyBodyBold: 'never stored permanently',
    privacyBodyAfter: '. We only read transaction rows to build your history.',
    maskedAccountNote: 'Account number masked on import',
    processingTitle: 'Processing statement…',
    processingSub: 'Masking account details · parsing transactions · detecting duplicates',
    transactionsFound: (n: number) => `${n} transactions found`,
    possibleDuplicates: (n: number) => `${n} possible duplicates`,
    tableHeaders: { date: 'Date', description: 'Description', category: 'Category', amount: 'Amount', import: 'Import' },
    duplicateNote: '⚠ Duplicate — already imported',
    importBtn: (n: number) => `Import ${n} transactions`,
    duplicatesSkipped: (n: number) => `${n} duplicates skipped automatically`,
    toastImported: (n: number) => `${n} transactions imported`,
  },

  scanReceipt: {
    dragTitle: 'Drag a receipt here',
    dragSub: "Snap a photo or upload — we'll read the merchant, date and total for you.",
    takePhoto: 'Take photo',
    uploadFile: 'Upload file',
    fileHint: 'JPG, PNG or PDF · up to 10 MB',
    idleTitle: 'Extracted details appear here',
    idleSub: 'Upload a receipt and review the parsed transaction before saving.',
    readingTitle: 'Reading your receipt…',
    steps: ['Enhancing image quality', 'Detecting merchant & date', 'Extracting line items & total'],
    confidenceBanner: (pct: number) => `Extracted with ${pct}% confidence · review below`,
    merchantLabel: 'Merchant',
    dateLabel: 'Date',
    totalLabel: 'Total',
    categoryLabel: 'Category ·',
    suggestedLabel: 'suggested',
    lineItemsLabel: 'Line items',
    duplicateBannerLead: 'Possible duplicate',
    duplicateBannerRest: (amount: string, date: string) => `— similar ${amount} charge on ${date}. Save anyway?`,
    confirmSave: 'Confirm & save',
    retry: 'Retry',
    toastSaved: 'Receipt saved to transactions',
  },

  settings: {
    editProfile: 'Edit profile',
    planSuffix: 'plan',
    freePlanFallback: 'Free',
    preferences: 'Preferences',
    currency: 'Currency',
    currencySub: 'Used across the app',
    currencyValue: 'Indian Rupee (₹)',
    budgetResetDay: 'Budget reset day',
    budgetResetSub: 'When your monthly budget restarts',
    budgetResetValue: '1st of month',
    theme: 'Theme',
    themeSub: 'App appearance',
    themeTabs: { light: 'Light', dark: 'Dark', auto: 'Auto' },
    privacySecurity: 'Privacy & Security',
    toggles: {
      maskAccountNumbers: { label: 'Mask account numbers', sub: 'Hide digits from imported statements' },
      biometricLock: { label: 'Biometric app lock', sub: 'Require Face ID / Touch ID to open' },
      autoDeleteRawUploads: {
        label: 'Auto-delete raw uploads',
        sub: 'Remove receipt and statement files after processing',
      },
      usageAnalytics: { label: 'Usage analytics', sub: 'Share anonymous usage data to improve SpendWise' },
    },
    data: 'Data',
    exportAllData: 'Export all data',
    exportAllDataSub: 'Download everything as CSV',
    exporting: 'Exporting…',
    deleteAccount: 'Delete account',
    deleteAccountSub: 'Permanently erase your data',
    exportFilename: 'spendwise-data.csv',
    toasts: {
      couldNotLoad: 'Could not load settings',
      saved: 'Preferences saved',
      couldNotSavePrefs: 'Could not save preferences',
      couldNotSaveSetting: 'Could not save setting',
      exportDownloaded: 'Export downloaded',
      exportFailed: 'Export failed',
      deleteDisabled: 'Account deletion is disabled in the demo',
    },
  },

  auth: {
    login: {
      title: 'Welcome back',
      subtitle: 'Sign in to keep your spending wise.',
      email: 'Email',
      password: 'Password',
      signIn: 'Sign in',
      signingIn: 'Signing in…',
      newHere: 'New here?',
      createAccount: 'Create an account',
      fallbackError: 'Could not sign in. Please try again.',
    },
    register: {
      title: 'Create your account',
      subtitle: 'A few seconds to smarter spending.',
      name: 'Name',
      email: 'Email',
      password: 'Password',
      minChars: 'Minimum 8 characters',
      createAccount: 'Create account',
      creatingAccount: 'Creating account…',
      alreadyHaveAccount: 'Already have an account?',
      signIn: 'Sign in',
      fallbackError: 'Could not create your account. Please try again.',
      welcomeToast: 'Welcome to SpendWise',
    },
  },
} as const;
